public class Aircraft implements FlyBehaviour{
    private String model;
    private String propulsion;

    public Aircraft(String model, String propulsion) {
        this.model = model;
        this.propulsion = propulsion;
    }

    @Override
    public void takeOffProcess() {
        System.out.printf("The thrust generated by %s at V1 speed is used generate the lift with the help of %s's flaps",propulsion, model);
    }

    @Override
    public void flight() {
        System.out.println(model + " maintains flight through the glide provided by the wings");
    }

    @Override
    public void speedMaintainance() {
        System.out.println(model + " maintains speed by the thrust from the jet engines");
    }

    @Override
    public void landing() {
        System.out.printf("To reduce the speed, %s extends the flap and let the landing gear down", model);
    }
}
